name: Deploy School App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/School_management_app
            
            # 1. On force la mise de côté des modifs locales (comme la sécu Mongo)
            git stash
            
            # 2. On récupère le code proprement
            git pull origin main
            
            # 3. On tente de remettre tes modifs. Si ça bloque, on continue quand même
            git stash pop || true
            
            # 4. On build le frontend SANS CACHE (pour être sûr d'avoir les nouvelles vues)
            docker compose build --no-cache frontend
            
            # 5. On relance tout
            docker compose up -d
            
            # 6. Nettoyage pour économiser les Go du VPS
            docker image prune -f
